#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8DTiny v0.1 * Central controlling device                                 |
# | Copyright (C) 2021 Pozsar Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | start                                                                      |
# | start with sudo                                                            |
# +----------------------------------------------------------------------------+

sudo ./mm8dty
